export default {
  page1: [
    { title: '1. Two Sum' },
    { title: '2. Add Two Numbers' },
    { title: '3. Longest Substring Without Repeating Characters' },
    { title: '4. Median of Two Sorted Arrays' },
    { title: '5. Longest Palindromic Substring' },
    { title: '6. Zigzag Conversion' },
    { title: '7. Reverse Integer' },
    { title: '8. String to Integer (atoi)' },
    { title: '9. Palindrome Number' },
    { title: '10. Regular Expression Matching' },
    { title: '11. Container With Most Water' },
    { title: '12. Integer to Roman' },
    { title: '13. Roman to Integer' },
    { title: '14. Longest Common Prefix' },
    { title: '15. 3Sum' },
    { title: '16. 3Sum Closest' },
    { title: '17. Letter Combinations of a Phone Number' },
    { title: '18. 4Sum' },
    { title: '19. Remove Nth Node From End of List' },
    { title: '20. Valid Parentheses' },
  ],
  page2: [
    { title: '21. Merge Two Sorted Lists' },
    { title: '22. Generate Parentheses' },
    { title: '23. Merge k Sorted Lists' },
    { title: '24. Swap Nodes in Pairs' },
    { title: '25. Reverse Nodes in k-Group' },
    { title: '26. Remove Duplicates from Sorted Array' },
    { title: '27. Remove Element' },
    { title: '28. Find the Index of the First Occurrence in a String' },
    { title: '29. Divide Two Integers' },
    { title: '30. Substring with Concatenation of All Words' },
    { title: '31. Next Permutation' },
    { title: '32. Longest Valid Parentheses' },
    { title: '33. Search in Rotated Sorted Array' },
    { title: '34. Find First and Last Position of Element in Sorted Array' },
    { title: '35. Search Insert Position' },
    { title: '36. Valid Sudoku' },
    { title: '37. Sudoku Solver' },
    { title: '38. Count and Say' },
    { title: '39. Combination Sum' },
    { title: '40. Combination Sum II' },
  ],
  page3: [
    { title: '41. First Missing Positive' },
    { title: '42. Trapping Rain Water' },
    { title: '43. Multiply Strings' },
    { title: '44. Wildcard Matching' },
    { title: '45. Jump Game II' },
    { title: '46. Permutations' },
    { title: '47. Permutations II' },
    { title: '48. Rotate Image' },
    { title: '49. Group Anagrams' },
    { title: '50. Pow(x, n)' },
    { title: '51. N-Queens' },
    { title: '52. N-Queens II' },
    { title: '53. Maximum Subarray' },
    { title: '54. Spiral Matrix' },
    { title: '55. Jump Game' },
    { title: '56. Merge Intervals' },
    { title: '57. Insert Interval' },
    { title: '58. Length of Last Word' },
    { title: '59. Spiral Matrix II' },
    { title: '60. Permutation Sequence' },
  ],
  page4: [
    { title: '61. Rotate List' },
    { title: '62. Unique Paths' },
    { title: '63. Unique Paths II' },
    { title: '64. Minimum Path Sum' },
    { title: '65. Valid Number' },
    { title: '66. Plus One' },
    { title: '67. Add Binary' },
    { title: '68. Text Justification' },
    { title: '69. Sqrt(x)' },
    { title: '70. Climbing Stairs' },
    { title: '71. Simplify Path' },
    { title: '72. Edit Distance' },
    { title: '73. Set Matrix Zeroes' },
    { title: '74. Search a 2D Matrix' },
    { title: '75. Sort Colors' },
    { title: '76. Minimum Window Substring' },
    { title: '77. Combinations' },
    { title: '78. Subsets' },
    { title: '79. Word Search' },
    { title: '80. Remove Duplicates from Sorted Array II' },
  ],
  page5: [
    { title: '81. Search in Rotated Sorted Array II' },
    { title: '82. Remove Duplicates from Sorted List II' },
    { title: '83. Remove Duplicates from Sorted List' },
    { title: '84. Largest Rectangle in Histogram' },
    { title: '85. Maximal Rectangle' },
    { title: '86. Partition List' },
    { title: '87. Scramble String' },
    { title: '88. Merge Sorted Array' },
    { title: '89. Gray Code' },
    { title: '90. Subsets II' },
    { title: '91. Decode Ways' },
    { title: '92. Reverse Linked List II' },
    { title: '93. Restore IP Addresses' },
    { title: '94. Binary Tree Inorder Traversal' },
    { title: '95. Unique Binary Search Trees II' },
    { title: '96. Unique Binary Search Trees' },
    { title: '97. Interleaving String' },
    { title: '98. Validate Binary Search Tree' },
    { title: '99. Recover Binary Search Tree' },
    { title: '100. Same Tree' },
  ],
};
