<script lang="ts" setup>
import { onUnmounted } from 'vue';

import TextField from '~/components/TextField.vue';
import Button from '~/components/Button.vue';
import Spinner from '~/components/Spinner.vue';
import Link from '~/components/Link.vue';

import useStore from './store';
import useLocale from './locales';
import useSchema from './schema';

defineRegistry({
  layout: 'Center',
});

const { state, actions, $reset } = useStore();
const locale = useLocale();
const schema = useSchema();

function signIn() {
  if (schema.validate()) {
    actions.signIn();
  }
}

onUnmounted(() => {
  $reset();
});
</script>

<template>
  <div class="w-full max-w-sm">
    <form
      v-if="!state.otpEnabled"
      class="bg-white dark:bg-slate-800 shadow-md rounded px-8 pt-6 pb-8"
    >
      <div class="mb-8">
        <div class="text-slate-900 dark:text-white font-bold text-xl mb-2">{{ locale.title }}</div>
        <div>{{ locale.subtitle }}</div>
      </div>

      <div class="mb-4">
        <TextField
          v-model:value="state.signInForm.username"
          required
          :errorMessage="state.errors.username"
          :disabled="state.signedIn"
        >
          {{ locale.username }}
        </TextField>
      </div>

      <div class="mb-8">
        <TextField
          v-model:value="state.signInForm.password"
          type="password"
          required
          :errorMessage="state.errors.password"
          :disabled="state.signedIn"
        >
          {{ locale.password }}
        </TextField>
      </div>

      <Button id="sign-in" :disabled="state.signedIn" class="w-full mb-4" @click="signIn">
        <Spinner v-if="state.signedIn" class="w-5 h-5 align-middle" />
        <div v-else>{{ locale.signIn }}</div>
      </Button>

      <div class="text-center">
        <Link to="/forgot-password">{{ locale.forgotPassword }}</Link>
      </div>
    </form>

    <form v-else class="bg-white dark:bg-slate-800 shadow-md rounded px-8 pt-6 pb-8">
      <div class="mb-8">
        <div class="text-slate-900 dark:text-white font-bold text-xl mb-2">
          Two-factor Authentication
        </div>
        <div>Enter verification code</div>
      </div>

      <div class="mb-6 space-y-2">
        <div>Enter the 6-digit authentication code generated by your app:</div>
        <TextField
          v-model:value="state.code"
          class="text-center"
          maxlength="6"
          @input.stop="actions.inputCode"
        />
      </div>

      <div class="text-center">
        <Link
          to="/sign-in"
          class="flex justify-center"
          @click="
            state.otpEnabled = false;
            state.signedIn = false;
          "
        >
          <div class="i-ic-round-arrow-back w-5 h-5"></div>
          <div>Back to sign in</div>
        </Link>
      </div>
    </form>
  </div>
</template>
