FROM node:8

ENV HOME /Vue-FullStarter-Kit

WORKDIR ${HOME}
ADD . $HOME

RUN yarn install

ENV NODE_ENV production

# envs --
ENV SITE_URL https://vue-by-example.firebaseapp.com

ENV FUNC_URL https://us-central1-vue-by-example.cloudfunctions.net
# -- envs

RUN yarn build:app
RUN yarn build:api && cd functions && yarn install
