services:
  - name: vue-starter
    type: web
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /

    dockerfilePath: ./infra/Dockerfile

    envVars:
      - key: SITE_ADDRESS
        value: 0.0.0.0:10000
