export default {
  title: `Sign in to our platform`,
  subtitle: `Login here using your username and password`,
  username: `Username`,
  password: `Password`,
  signIn: `Sign In`,
  forgotPassword: `Forgot Password?`,

  mfaTitle: `Multi-factor Authentication`,
  mfaSubtitle: `Enter verification code`,
  mfaHint: `Enter the 6-digit authentication code generated by your app:`,
  backToSignIn: `Back to sign in`,
};
