version: 2.1

jobs:
  build-test-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up -d ci
      - run: docker-compose exec ci pnpm build
      - run: docker-compose exec ci pnpm unit

workflows:
  workflow:
    jobs:
      - build-test-deploy
