version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up -d ci
      - run: docker-compose exec ci pnpm build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run: docker-compose exec ci pnpm unit

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
