<script lang="ts" setup>
import { reactive } from 'vue';
import { RouterLink } from 'vue-router';

import TextField from '~/components/TextField.vue';
import Button from '~/components/Button.vue';
import Spinner from '~/components/Spinner.vue';
import { useFetch } from '~/composables';

import useLocale from './_locales';
import { useState, useActions } from './provider';
import { useSignInFormSchema } from './schema';

const authOtpValidate = useFetch('/auth/otp/validate').json();

const locale = useLocale();
const state = useState();
const actions = useActions();
const schema = useSignInFormSchema();

const flux = reactive({
  signIn() {
    if (schema.validate()) {
      actions.signIn();
    }
  },

  code: '',
  async inputCode() {
    if (flux.code.length === 6) {
      await authOtpValidate
        .post({
          code: flux.code,
          username: state.signInForm.username,
          password: state.signInForm.password,
        })
        .execute();

      if (authOtpValidate.statusCode.value === 200) {
        const { accessToken, refreshToken } = authOtpValidate.data.value;
        actions.twoFactor(accessToken, refreshToken);
      }
    }
  },
});
</script>

<template>
  <div class="w-full max-w-sm">
    <form
      v-if="!state.otpEnabled"
      class="bg-white dark:bg-slate-800 shadow-md rounded px-8 pt-6 pb-8"
    >
      <div class="mb-8">
        <div class="text-slate-900 dark:text-white font-bold text-xl mb-2">{{ locale.title }}</div>
        <div>{{ locale.subtitle }}</div>
      </div>

      <div class="mb-4">
        <TextField
          v-model:value="state.signInForm.username"
          required
          :errorMessage="state.errors['signInForm.username']"
          :disabled="state.signedIn"
        >
          {{ locale.username }}
        </TextField>
      </div>

      <div class="mb-8">
        <TextField
          v-model:value="state.signInForm.password"
          type="password"
          required
          :errorMessage="state.errors['signInForm.password']"
          :disabled="state.signedIn"
        >
          {{ locale.password }}
        </TextField>
      </div>

      <Button id="sign-in" :disabled="state.signedIn" class="w-full mb-4" @click="flux.signIn">
        <Spinner v-if="state.signedIn" class="w-5 h-5 border-2 align-middle" />
        <div v-else>{{ locale.signIn }}</div>
      </Button>

      <div class="text-center">
        <RouterLink
          class="font-bold text-sm text-blue-500 hover:text-blue-600 dark:hover:text-blue-400"
          to="/auth/forgot-password"
        >
          {{ locale.forgotPassword }}
        </RouterLink>
      </div>
    </form>

    <form v-else class="bg-white dark:bg-slate-800 shadow-md rounded px-8 pt-6 pb-8">
      <div class="mb-8">
        <div class="text-slate-900 dark:text-white font-bold text-xl mb-2">
          Two-factor Authentication
        </div>
        <div>Enter verification code</div>
      </div>

      <div class="mb-6 space-y-2">
        <div>Enter the 6-digit authentication code generated by your app:</div>
        <TextField
          v-model:value="flux.code"
          class="text-center"
          maxlength="6"
          @input.stop="flux.inputCode"
        />
      </div>

      <div class="text-center">
        <div
          class="inline-flex font-bold text-sm text-blue-500 hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer"
          @click="
            state.otpEnabled = false;
            state.signedIn = false;
          "
        >
          <div class="i-ic-round-arrow-back w-5 h-5"></div>
          <div>Back to sign in</div>
        </div>
      </div>
    </form>
  </div>
</template>
