export default [
  { id: 1, title: '1. Two Sum', difficulty: 'Easy' },
  { id: 2, title: '2. Add Two Numbers', difficulty: 'Medium' },
  { id: 3, title: '3. Longest Substring Without Repeating Characters', difficulty: 'Medium' },
  { id: 4, title: '4. Median of Two Sorted Arrays', difficulty: 'Hard' },
  { id: 5, title: '5. Longest Palindromic Substring', difficulty: 'Medium' },
  { id: 6, title: '6. Zigzag Conversion', difficulty: 'Medium' },
  { id: 7, title: '7. Reverse Integer', difficulty: 'Medium' },
  { id: 8, title: '8. String to Integer (atoi)', difficulty: 'Medium' },
  { id: 9, title: '9. Palindrome Number', difficulty: 'Easy' },
  { id: 10, title: '10. Regular Expression Matching', difficulty: 'Hard' },
  { id: 11, title: '11. Container With Most Water', difficulty: 'Medium' },
  { id: 12, title: '12. Integer to Roman', difficulty: 'Medium' },
  { id: 13, title: '13. Roman to Integer', difficulty: 'Easy' },
  { id: 14, title: '14. Longest Common Prefix', difficulty: 'Easy' },
  { id: 15, title: '15. 3Sum', difficulty: 'Medium' },
  { id: 16, title: '16. 3Sum Closest', difficulty: 'Medium' },
  { id: 17, title: '17. Letter Combinations of a Phone Number', difficulty: 'Medium' },
  { id: 18, title: '18. 4Sum', difficulty: 'Medium' },
  { id: 19, title: '19. Remove Nth Node From End of List', difficulty: 'Medium' },
  { id: 20, title: '20. Valid Parentheses', difficulty: 'Easy' },
  { id: 21, title: '21. Merge Two Sorted Lists', difficulty: 'Easy' },
  { id: 22, title: '22. Generate Parentheses', difficulty: 'Medium' },
  { id: 23, title: '23. Merge k Sorted Lists', difficulty: 'Easy' },
  { id: 24, title: '24. Swap Nodes in Pairs', difficulty: 'Medium' },
  { id: 25, title: '25. Reverse Nodes in k-Group', difficulty: 'Easy' },
  { id: 26, title: '26. Remove Duplicates from Sorted Array', difficulty: 'Easy' },
  { id: 27, title: '27. Remove Element', difficulty: 'Easy' },
  { id: 28, title: '28. Find the Index of the First Occurrence in a String', difficulty: 'Easy' },
  { id: 29, title: '29. Divide Two Integers', difficulty: 'Medium' },
  { id: 30, title: '30. Substring with Concatenation of All Words', difficulty: 'Easy' },
  { id: 31, title: '31. Next Permutation', difficulty: 'Medium' },
  { id: 32, title: '32. Longest Valid Parentheses', difficulty: 'Easy' },
  { id: 33, title: '33. Search in Rotated Sorted Array', difficulty: 'Easy' },
  {
    id: 34,
    title: '34. Find First and Last Position of Element in Sorted Array',
    difficulty: 'Easy',
  },
  { id: 35, title: '35. Search Insert Position', difficulty: 'Easy' },
  { id: 36, title: '36. Valid Sudoku', difficulty: 'Easy' },
  { id: 37, title: '37. Sudoku Solver', difficulty: 'Easy' },
  { id: 38, title: '38. Count and Say', difficulty: 'Easy' },
  { id: 39, title: '39. Combination Sum', difficulty: 'Easy' },
  { id: 40, title: '40. Combination Sum II', difficulty: 'Easy' },
  { id: 41, title: '41. First Missing Positive', difficulty: 'Easy' },
  { id: 42, title: '42. Trapping Rain Water', difficulty: 'Easy' },
  { id: 43, title: '43. Multiply Strings', difficulty: 'Easy' },
  { id: 44, title: '44. Wildcard Matching', difficulty: 'Easy' },
  { id: 45, title: '45. Jump Game II', difficulty: 'Easy' },
  { id: 46, title: '46. Permutations', difficulty: 'Easy' },
  { id: 47, title: '47. Permutations II', difficulty: 'Easy' },
  { id: 48, title: '48. Rotate Image', difficulty: 'Easy' },
  { id: 49, title: '49. Group Anagrams', difficulty: 'Easy' },
  { id: 50, title: '50. Pow(x, n)', difficulty: 'Easy' },
  { id: 51, title: '51. N-Queens', difficulty: 'Easy' },
  { id: 52, title: '52. N-Queens II', difficulty: 'Easy' },
  { id: 53, title: '53. Maximum Subarray', difficulty: 'Easy' },
  { id: 54, title: '54. Spiral Matrix', difficulty: 'Easy' },
  { id: 55, title: '55. Jump Game', difficulty: 'Easy' },
  { id: 56, title: '56. Merge Intervals', difficulty: 'Easy' },
  { id: 57, title: '57. Insert Interval', difficulty: 'Easy' },
  { id: 58, title: '58. Length of Last Word', difficulty: 'Easy' },
  { id: 59, title: '59. Spiral Matrix II', difficulty: 'Easy' },
  { id: 60, title: '60. Permutation Sequence', difficulty: 'Easy' },
  { id: 61, title: '61. Rotate List', difficulty: 'Easy' },
  { id: 62, title: '62. Unique Paths', difficulty: 'Easy' },
  { id: 63, title: '63. Unique Paths II', difficulty: 'Easy' },
  { id: 64, title: '64. Minimum Path Sum', difficulty: 'Easy' },
  { id: 65, title: '65. Valid Number', difficulty: 'Easy' },
  { id: 66, title: '66. Plus One', difficulty: 'Easy' },
  { id: 67, title: '67. Add Binary', difficulty: 'Easy' },
  { id: 68, title: '68. Text Justification', difficulty: 'Easy' },
  { id: 69, title: '69. Sqrt(x)', difficulty: 'Easy' },
  { id: 70, title: '70. Climbing Stairs', difficulty: 'Easy' },
  { id: 71, title: '71. Simplify Path', difficulty: 'Easy' },
  { id: 72, title: '72. Edit Distance', difficulty: 'Easy' },
  { id: 73, title: '73. Set Matrix Zeroes', difficulty: 'Easy' },
  { id: 74, title: '74. Search a 2D Matrix', difficulty: 'Easy' },
  { id: 75, title: '75. Sort Colors', difficulty: 'Easy' },
  { id: 76, title: '76. Minimum Window Substring', difficulty: 'Easy' },
  { id: 77, title: '77. Combinations', difficulty: 'Easy' },
  { id: 78, title: '78. Subsets', difficulty: 'Easy' },
  { id: 79, title: '79. Word Search', difficulty: 'Easy' },
  { id: 80, title: '80. Remove Duplicates from Sorted Array II', difficulty: 'Easy' },
  { id: 81, title: '81. Search in Rotated Sorted Array II', difficulty: 'Easy' },
  { id: 82, title: '82. Remove Duplicates from Sorted List II', difficulty: 'Easy' },
  { id: 83, title: '83. Remove Duplicates from Sorted List', difficulty: 'Easy' },
  { id: 84, title: '84. Largest Rectangle in Histogram', difficulty: 'Easy' },
  { id: 85, title: '85. Maximal Rectangle', difficulty: 'Easy' },
  { id: 86, title: '86. Partition List', difficulty: 'Easy' },
  { id: 87, title: '87. Scramble String', difficulty: 'Easy' },
  { id: 88, title: '88. Merge Sorted Array', difficulty: 'Easy' },
  { id: 89, title: '89. Gray Code', difficulty: 'Easy' },
  { id: 90, title: '90. Subsets II', difficulty: 'Easy' },
  { id: 91, title: '91. Decode Ways', difficulty: 'Easy' },
  { id: 92, title: '92. Reverse Linked List II', difficulty: 'Easy' },
  { id: 93, title: '93. Restore IP Addresses', difficulty: 'Easy' },
  { id: 94, title: '94. Binary Tree Inorder Traversal', difficulty: 'Easy' },
  { id: 95, title: '95. Unique Binary Search Trees II', difficulty: 'Easy' },
  { id: 96, title: '96. Unique Binary Search Trees', difficulty: 'Easy' },
  { id: 97, title: '97. Interleaving String', difficulty: 'Easy' },
  { id: 98, title: '98. Validate Binary Search Tree', difficulty: 'Easy' },
  { id: 99, title: '99. Recover Binary Search Tree', difficulty: 'Easy' },
  { id: 100, title: '100. Same Tree', difficulty: 'Easy' },
];
