<script lang="ts" setup>
import { reactive } from 'vue';
import QrcodeImage from 'vue-qrcode-image';

import Breadcrumbs from '~/components/Breadcrumbs.vue';
import TextField from '~/components/TextField.vue';
import Button from '~/components/Button.vue';

const flux = reactive({
  os: 'ios',

  flow: 1,
});
</script>

<template>
  <Breadcrumbs
    :items="[
      { text: 'Settings', disabled: true },
      { text: 'Two-factor Authentication', disabled: true },
    ]"
    class="mb-4"
  />

  <div class="mb-4">
    <div class="text-3xl font-bold">Two-factor Authentication</div>
  </div>

  <div class="bg-white dark:bg-slate-800 rounded-md shadow-lg px-6 py-5 w-125">
    <div class="text-xl font-bold">Turn on Two-step Verification</div>

    <template v-if="flux.flow === 1">
      <div class="mt-3 mb-6">Get verification codes with Google Authenticator</div>

      <div
        class="relative flex w-full bg-slate-50 dark:bg-slate-700 shadow rounded-t-xl p-3 transition-colors"
      >
        <input
          id="radio-1"
          v-model="flux.os"
          type="radio"
          name="tabs"
          value="ios"
          class="hidden z-2"
        />
        <label class="z-2 flex justify-center items-center h-12 flex-1 cursor-pointer" for="radio-1"
          >iPhone & iPad</label
        >
        <input
          id="radio-2"
          v-model="flux.os"
          type="radio"
          name="tabs"
          value="android"
          class="hidden z-2"
        />
        <label class="z-2 flex justify-center items-center h-12 flex-1 cursor-pointer" for="radio-2"
          >Android</label
        >
        <span
          class="glider absolute flex z-1 h-12 rounded-xl bg-slate-200 transition-transform"
        ></span>
      </div>

      <div class="flex justify-center items-center bg-slate-50 dark:bg-slate-700 p-4 mb-6">
        <QrcodeImage
          v-if="flux.os === 'ios'"
          value="https://apps.apple.com/app/google-authenticator/id388497605"
          :size="5"
          class="w-50 rounded-md"
        />

        <QrcodeImage
          v-if="flux.os === 'android'"
          value="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"
          :size="4"
          class="w-50 rounded-md"
        />
      </div>

      <div class="text-center">
        <Button color="primary" class="w-1/3" @click="flux.flow = 2">Next</Button>
      </div>
    </template>

    <template v-if="flux.flow === 2">
      <div>Scan the QR code into your app.</div>

      <QrcodeImage
        value="otpauth://totp/Fastify%20Starter:shyam.chen?secret=CANACAIVIRPXM23E&period=30&digits=6&algorithm=SHA1&issuer=Fastify%20Starter"
        :size="4"
        class="w-50 rounded-md"
      />

      <div class="text-center space-x-4">
        <Button color="secondary" class="w-1/3" @click="flux.flow = 1">Back</Button>
        <Button color="primary" class="w-1/3" @click="flux.flow = 3">Next</Button>
      </div>
    </template>

    <template v-if="flux.flow === 3">
      <div>Enter the 6-digit authentication code generated by your app:</div>

      <TextField class="text-center" maxlength="6" />

      <div class="text-center space-x-4">
        <Button color="secondary" class="w-1/3" @click="flux.flow = 2">Back</Button>
        <Button color="primary" class="w-1/3" @click="flux.flow = 4">Next</Button>
      </div>
    </template>

    <template v-if="flux.flow === 4">
      <div class="w-12 h-12 i-lucide-check-circle text-green-500 mx-auto my-0 mb-6"></div>
    </template>
  </div>
</template>

<style lang="scss" scoped>
input[type='radio'] {
  &:checked + label {
    @apply text-blue-600;
  }
}

input[id='radio-1'] {
  &:checked ~ .glider {
    @apply translate-x-0;
  }
}

input[id='radio-2'] {
  &:checked ~ .glider {
    @apply translate-x-1/1;
  }
}

.glider {
  width: 214px;
}
</style>
